### ISSUE TITLE
Clone to alternate host and resource pool

### ISSUE THREAD

**Issue by mkuzmin** [LizaTretyakova/packer-builder-vsphere#4]
Add `host` and `resource_pool` options to clone VMs into different ESXi hosts and/or resource pools
https://github.com/mkuzmin/terraform-provider-vmware/blob/master/resource_virtual_machine.go#L208

**Comment by mkuzmin** [comment]
No need to support clusters for now

**Comment by mkuzmin** [comment]
target host is mandatory, pool is optional (by default - root of the host)

**Comment by LizaTretyakova** [comment]
Implemented in #14.
